### ISSUE TITLE
Installation documentation ?

### ISSUE THREAD

**Issue by chrsc59** [vlebourl/custom_homepluscontrol#2]
Can you add some documentation for installation and tests please ?

I want to test the Shutters integration, I have no other Legrand device, and found your integration in https://github.com/chemaaa/homepluscontrol/issues/4#issuecomment-939248084

I tried several methods 
- with and without the official integration installed
- via HACS after adding the github store but no Install button in HACS so hamburger menu>reinstall, and manually by downloading the zip and copying custom_homepluscontrol-main in the custom_components folder
(and yes restarting the server)

In any case, no device/entity is discovered so I believe I only ended with starting the official integration, hence no device to discover.

Please note that 
- installation of the official integration was successful (although configuration was painful on the Legrand part), 
- I'm French so my English wording may be approximative
- I understant this moght be a beta version (or even alpha)
- and more importantly, I am relatively new to home assistant, and still confused with HACS vs. Configuration>Integrations... 

Thanks

**Comment by vlebourl** [comment]
I added a README with info for installation. Let me know if that's enough for you.

**Comment by chrsc59** [comment]
Thanks, 
I did that already, and does not help.

Meanwhile I found an error in the logs from the Legrand API so I need to investigate this.

You can close the current issue, as the installation documentation is fine (I just don't know which integration is running, yours or the official one, same displayed name...).
Thanks

**Comment by vlebourl** [comment]
It's the same name on purpose so that the custom integration overrides the official one. If you tried installing both and are a bit lost, you could try to remove the integration from the integration panel on the configuration menu, then restart home assistant, then re-add the integration. All this without uninstalling from HACS. this should ensure you're actually using the custom integration. 
You can also turn debugging on for the custom integration in you're configuration.yaml (https://github.com/vlebourl/custom_homepluscontrol/blob/main/README.md#enable-debug-logging)

**Comment by chrsc59** [comment]
Thanks, 
So I understand now that custom_components / HACS repositories **override** the official repository/integrations
That seems to work now, the blinders have been found, so I will now do some tests (I do not have blinders that return state however)

FYI, what I did was : 

- Delete Home + Control integration
- Remove custom Home + integration repository
- Restart HA server

- Install Legrand Home + Control Integration via config>add new...
- Accept eliotbylegrand access
- Confirm error in logs
- >>>> Fix key error (one character was missing in the subscription key)
- Restart HA server

- Install Legrand Home + Control integration 
- check logs for no error
- Delete integration

- Add custom integration repository 
- restart HA server
- Install integration via config>add new...
- Accept eliotbylegrand access
- OK no error in logs
- Delete integration

- Install custom integration folder in custom_components
- restart HA server
- Add the integration via Config>add new
- Accept eliotbylegrand access
- Check no error
- A popup to configure the devices appeared at some point => OK
